# Default initial positions for table_streeing_arm's ros2_control fake system

initial_positions:
  joint_1: 0
  joint_10: 0
  joint_11: 0
  joint_2: 0
  joint_3: 0
  joint_4: 0
  joint_5: 0
  joint_6: 0
  joint_7: 0
  joint_8: 0
  joint_9: 0