# Complete MoveIt controllers configuration

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - arm_group_controller
    - gripper_controller

  arm_group_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5

  gripper_controller:
    type: GripperCommand
    action_ns: gripper_action
    joints:
      - joint_6
    # 夹爪参数
    parallel_gripper: true
    default_max_effort: 5.0
    default_velocity: 0.1 