# Complete ros2_controllers configuration with arm and gripper
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    arm_group_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    gripper_controller:
      type: position_controllers/JointGroupPositionController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

arm_group_controller:
  ros__parameters:
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.05
      goal_time: 2.0  # 允许2秒的目标时间容差
      joint_1:
        trajectory: 0.2  # 增加轨迹容差
        goal: 0.1        # 增加目标容差
      joint_2:
        trajectory: 0.2
        goal: 0.1
      joint_3:
        trajectory: 0.2
        goal: 0.1
      joint_4:
        trajectory: 0.2
        goal: 0.1
      joint_5:
        trajectory: 0.2
        goal: 0.1

gripper_controller:
  ros__parameters:
    joints:
      - joint_6
    command_interfaces:
      - position
    state_interfaces:
      - position 