# This config file is used by ros2_control for real hardware
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    arm_group_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

arm_group_controller:
  ros__parameters:
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 0.0
      joint_1:
        trajectory: 0.1
        goal: 0.05
      joint_2:
        trajectory: 0.1
        goal: 0.05
      joint_3:
        trajectory: 0.1
        goal: 0.05
      joint_4:
        trajectory: 0.1
        goal: 0.05
      joint_5:
        trajectory: 0.1
        goal: 0.05
      joint_6:
        trajectory: 0.1
        goal: 0.05 