# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    arm_group_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    gripper_group_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

arm_group_controller:
  ros__parameters:
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
gripper_group_controller:
  ros__parameters:
    joints:
      - joint_6
      - joint_10
      - joint_7
      - joint_11
      - joint_8
      - joint_9
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity